### ISSUE TITLE
Add missing dependencies to `package.json`

### ISSUE THREAD

**Issue by Fdawgs** [TauntonandSomersetNHSTrust/contextual_launcher#6]
Both dependencies are imported but never declared in package.json, so imports will never be resolved:

https://github.com/TauntonandSomersetNHSTrust/contextual_launcher/blob/4ac08708032394c7683679f3288b2f9ae1feec80/src/server.js#L22

https://github.com/TauntonandSomersetNHSTrust/contextual_launcher/blob/4ac08708032394c7683679f3288b2f9ae1feec80/src/utils/in-memory-logger.js#L1

**Comment by nhshaydn** [comment]
body-parser is imported implicitly by express, winston-transport by winston. As I'm calling them explicitly, for consistency I'll add them to the package.json.
