### ISSUE TITLE
Use explicit semicolons

### ISSUE THREAD

**Issue by Fdawgs** [TauntonandSomersetNHSTrust/contextual_launcher#9]
Node's parser will implicitly insert a semicolon when it encounters a newline character in general however this is a dangerous feature since it can mask subtle errors and confuse readers; it should not be relied on.

See https://github.com/TauntonandSomersetNHSTrust/contextual_launcher/pull/2

**Comment by nhshaydn** [comment]
Good catch. I'm a semi-colon fan, but they can get forgotten in hippy languages like js. I'll look into a good linter.
